### ISSUE TITLE
share link copy bug maybe

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/codemoji#199]
@abusedmedia 

I think I found a bug. When I click copy in the share page, the link I got was httpss://mzl.la/1UFYrTI

The two s's in https looks like a bug.

Do you see this too?

**Comment by irowebbn** [comment]
I came here to file the same issue. It's definitely there. I tried using the contact link but the email it gives doesn't actually exist.

**Comment by abusedmedia** [comment]
The short url comes from the backend (https://bitly.mofoprod.net/generate/) and it comes already with the wrong 'httpss' from it, no responsibility in the front-end.

About the email, feel free to provide a real one, we can update the mailto: url or you can update it directly.

**Comment by irowebbn** [comment]
@abusedmedia Which email should I put there? (I'm not affiliated with mozilla, i don't know their mail structure)

**Comment by cadecairos** [comment]
The Bitly API was previously giving us shortened links that used http - [so a simple fix was put in place](https://github.com/mozilla/bitly-secret-service/commit/cd35b105a92dbeb29395f1b4a3f4448866874245)

For some reason, we're getting https prefixed links now, so I updated the replace with the `://` portion of the protocol, this way we can always be sure we're getting a properly formatted `https://` prefix.

**Comment by irowebbn** [comment]
@cadecairos Looks good now! Feel free to close the issue.

**Comment by cadecairos** [comment]
Thanks for hopping in and confirming the fix @irowebbn!
