### ISSUE TITLE
Explore embedded signup on share screen

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/codemoji#217]
As we start to plan snippet access, it would be great to consider adding some list growth options - I'd like to consider sending one cohort of users to a share page (after they share the emoji with a friend) that includes an embedded signup form.  Thoughts @andreawood ?

**Comment by damiankay** [comment]
Hey Brett - this slipped through the cracks. Should I follow up with TODO to see if this is possible? If so, I imagine we'll need a bit of UX work. Let me know and I can set up an alternate ticket in mofo/advocacy. 

Thanks

**Comment by damiankay** [comment]
Closing this issue and moving here:  https://github.com/MozillaFoundation/Advocacy/issues/89
